parameters:
    database_driver:   pdo_mysql
    database_host:     localhost

    database_port:     null

    database_user:     root

    database_password: root
    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    popular_parameter_days:  14
    popular_limit:     20

    artistes_return:     10

