parameters:
<<<<<<< HEAD

    database_driver: pdo_mysql
    database_host: localhost
    database_port: 8889
    database_name: projetindus
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true


    popular_parameter_days:  14
    popular_limit:     20
    artistes_return:     10


