byexample_demo_userrest:
    resource: ByExample\DemoBundle\Controller\UserRestController
    type: rest

byexample_demo_userrolrest:
    resource: ByExample\DemoBundle\Controller\UserRoleRestController
    type: rest
    parent: byexample_demo_userrest

byexample_genres:
    resource: ByExample\DemoBundle\Controller\GenreRestController
    type: rest